apiVersion: v1
kind: Secret
metadata:
  name: {{ include "demands.fullname" . }}-secrets
  labels:
    {{- include "demands.labels" . | nindent 4 }}
type: Opaque
data:
  postgres-password: {{ .Values.postgres.password | b64enc | quote }}
  keycloak-admin-password: {{ .Values.keycloak.adminPassword | b64enc | quote }}
  keycloak-client-secret: {{ .Values.server.env.KEYCLOAK_CLIENT_SECRET | b64enc | quote }}
