apiVersion: v1
kind: Service
metadata:
  name: {{ include "demands.fullname" . }}-server
  labels:
    app: server
    {{- include "demands.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.server.port }}
      targetPort: {{ .Values.server.port }}
      protocol: TCP
  selector:
    app: server
